const RAW_K = {
    mod1: [{k:'ア',r:'a'},{k:'イ',r:'i'},{k:'ウ',r:'u'},{k:'エ',r:'e'},{k:'オ',r:'o'}],
    mod2: [{k:'カ',r:'ka'},{k:'キ',r:'ki'},{k:'ク',r:'ku'},{k:'ケ',r:'ke'},{k:'コ',r:'ko'},{k:'サ',r:'sa'},{k:'シ',r:'shi'},{k:'ス',r:'su'},{k:'セ',r:'se'},{k:'ソ',r:'so'},{k:'タ',r:'ta'},{k:'チ',r:'chi'},{k:'ツ',r:'tsu'},{k:'テ',r:'te'},{k:'ト',r:'to'},{k:'ナ',r:'na'},{k:'ニ',r:'ni'},{k:'ヌ',r:'nu'},{k:'ネ',r:'ne'},{k:'ノ',r:'no'},{k:'ー',r:'-'}],
    mod3: [{k:"ハ",r:"ha"},{k:"ヒ",r:"hi"},{k:"フ",r:"fu"},{k:"ヘ",r:"he"},{k:"ホ",r:"ho"},{k:"マ",r:"ma"},{k:"ミ",r:"mi"},{k:"ム",r:"mu"},{k:"メ",r:"me"},{k:"モ",r:"mo"},{k:"ヤ",r:"ya"},{k:"ユ",r:"yu"},{k:"ヨ",r:"yo"},{k:"ラ",r:"ra"},{k:"リ",r:"ri"},{k:"ル",r:"ru"},{k:"レ",r:"re"},{k:"ロ",r:"ro"},{k:"ワ",r:"wa"},{k:"ヲ",r:"wo"},{k:"ン",r:"n"}],
    mod4: [{k:'ガ',r:'ga'},{k:'ギ',r:'gi'},{k:'グ',r:'gu'},{k:'ゲ',r:'ge'},{k:'ゴ',r:'go'},{k:'ザ',r:'za'},{k:'ジ',r:'ji'},{k:"ズ",r:"zu"},{k:"ゼ",r:"ze"},{k:"ゾ",r:"zo"},{k:"ダ",r:"da"},{k:"デ",r:"de"},{k:"ド",r:"do"},{k:"バ",r:"ba"},{k:"ビ",r:"bi"},{k:"ブ",r:"bu"},{k:"ベ",r:"be"},{k:"ボ",r:"bo"}],
    mod5: [{k:"パ",r:"pa"},{k:"ピ",r:"pi"},{k:"プ",r:"pu"},{k:"ペ",r:"pe"},{k:"ポ",r:"po"}],
    mod6: [{k:'キャ',r:'kya'},{k:'キュ',r:'kyu'},{k:'キョ',r:'kyo'},{k:'シャ',r:'sha'},{k:'シュ',r:'shu'},{k:'ショ',r:'sho'},{k:'チャ',r:'cha'},{k:'チュ',r:'chu'},{k:'チョ',r:'cho'},{k:'ニャ',r:'nya'},{k:'ニュ',r:'nyu'},{k:'ニョ',r:'nyo'},{k:'ヒャ',r:'hya'},{k:'ヒュ',r:'hyu'},{k:'ヒョ',r:'hyo'},{k:'ミャ',r:'mya'},{k:'ミュ',r:'myu'},{k:'ミョ',r:'myo'},{k:'リャ',r:'rya'},{k:'リュ',r:'ryu'},{k:'リョ',r:'ryo'},{k:'ギャ',r:'gya'},{k:'ギュ',r:'gyu'},{k:'ギョ',r:'gyo'},{k:'ジャ',r:'ja'},{k:'ジュ',r:'ju'},{k:'ジョ',r:'jo'},{k:'ビャ',r:'bya'},{k:'ビュ',r:'byu'},{k:"ビョ",r:"byo"},{k:"ピャ",r:"pya"},{k:"ピュ",r:"pyu"},{k:"ピョ",r:"pyo"},{k:"ファ",r:"fa"},{k:"フィ",r:"fi"},{k:"フェ",r:"fe"},{k:"フォ",r:"fo"},{k:"ティ",r:"ti"},{k:"ディ",r:"di"},{k:"ウェ",r:"we"},{k:"ウィ",r:"wi"},{k:"ウォ",r:"wo"},{k:"ヴァ",r:"va"},{k:"ヴィ",r:"vi"},{k:"ヴ",r:"vu"},{k:"ヴェ",r:"ve"},{k:"ヴォ",r:"vo"},{k:"チェ",r:"che"},{k:"ッ",r:"(pausa)"}],
    words_easy: [{k:'キス',r:'kisu', m:'Beijo'},{k:'テスト',r:'tesuto', m:'Teste'},{k:'ノート',r:'nooto', m:'Caderno'},{k:'ドア',r:'doa', m:'Porta'},{k:'パン',r:'pan', m:'Pão'},{k:'ペン',r:'pen', m:'Caneta'},{k:'バス',r:'basu', m:'Ônibus'},{k:'ケーキ',r:'keeki', m:'Bolo'},{k:'エア',r:'ea', m:'Ar'},{k:'アイ',r:'ai', m:'Olho'},{k:'トイレ',r:'toire', m:'Banheiro'},{k:'ベッド',r:'beddo', m:'Cama'},{k:'ペット',r:'petto', m:'Pet'},{k:'ソファ',r:'sofa', m:'Sofá'},{k:'クラス',r:'kurasu', m:'Classe'},{k:'コップ',r:'koppu', m:'Copo'},{k:'スープ',r:'suupu', m:'Sopa'},{k:'チーズ',r:'chiizu', m:'Queijo'},{k:'ツアー',r:'tsuaa', m:'Tour'},{k:'トマト',r:'tomato', m:'Tomate'},{k:'ハム',r:'hamu', m:'Presunto'},{k:'ビル',r:'biru', m:'Prédio'},{k:'プール',r:'puuru', m:'Piscina'},{k:'ベル',r:'beru', m:'Sino'},{k:'ボタン',r:'botan', m:'Botão'}],
    words_medium: [{k:'カメラ',r:'kamera', m:'Câmera'},{k:'ホテル',r:'hoteru', m:'Hotel'},{k:'ミルク',r:'miruku', m:'Leite'},{k:'タクシー',r:'takushii', m:'Táxi'},{k:'ワイン',r:'wain', m:'Vinho'},{k:'テレビ',r:'terebi', m:'TV'},{k:'ビデオ',r:'bideo', m:'Vídeo'},{k:'ピアノ',r:'piano', m:'Piano'},{k:'カフェ',r:'kafe', m:'Café'},{k:'シャツ',r:'shatsu', m:'Camisa'},{k:'アニメ',r:'anime', m:'Anime'},{k:'ギター',r:'gitaa', m:'Guitarra'},{k:'グラス',r:'gurasu', m:'Taça'},{k:'シャワー',r:'shawaa', m:'Chuveiro'},{k:'スイッチ',r:'suitchi', m:'Interruptor'},{k:'スプーン',r:'supuun', m:'Colher'},{k:'スポーツ',r:'supootsu', m:'Esportes'},{k:'ズボン',r:'zubon', m:'Calça'},{k:'タオル',r:'taoru', m:'Toalha'},{k:'チケット',r:'chiketto', m:'Ingresso'},{k:'ニュース',r:'nyuusu', m:'Notícias'},{k:'ネクタイ',r:'nekutai', m:'Gravata'},{k:'ナイフ',r:'naifu', m:'Faca'},{k:'バター',r:'bataa', m:'Manteiga'},{k:'フィルム',r:'firumu', m:'Filme'}],
    words_hard: [{k:'パソコン',r:'pasokon', m:'PC'},{k:'コンピューター',r:'konpyuutaa', m:'Computador'},{k:'チョコレート',r:'chokoreeto', m:'Chocolate'},{k:'パーティー',r:'paatii', m:'Festa'},{k:'インターフェース',r:'intaafeesu', m:'Interface'},{k:'スマートフォン',r:'sumaho', m:'Smartphone'},{k:'インターネット',r:'intaanetto', m:'Internet'},{k:'レストラン',r:'resutoran', m:'Restaurante'},{k:'マンション',r:'manshon', m:'Prédio'},{k:'スーパー',r:'suupaa', m:'Supermercado'},{k:'アルバイト',r:'arubaito', m:'Trabalho part-time'},{k:'エレベーター',r:'erebeetaa', m:'Elevador'},{k:'カレンダー',r:'karendaa', m:'Calendário'},{k:'コンサート',r:'konsaato', m:'Concerto'},{k:'スーパーマーケット',r:'suupaamaaketto', m:'Supermercado'},{k:'スケジュール',r:'sukejuuru', m:'Cronograma'},{k:'パスポート',r:'pasupooto', m:'Passaporte'},{k:'プラスチック',r:'purasuchikku', m:'Plástico'},{k:'プログラム',r:'puroguramu', m:'Programa'},{k:'ボールペン',r:'boorupen', m:'Caneta esf.'},{k:'マクドナルド',r:'makudonarudo', m:'McDonald\'s'},{k:'ヨーロッパ',r:'yooroppa', m:'Europa'},{k:'ロマンチック',r:'romanchikku', m:'Romântico'},{k:'ボランティア',r:'borantia', m:'Voluntário'},{k:'コミュニケーション',r:'komyunikeeshon', m:'Comunicação'}]
};

const ROMAJI_KATA_MAP = {'kya':'キャ','kyu':'キュ','kyo':'キョ','sha':'シャ','shu':'シュ','sho':'ショ','cha':'チャ','chu':'チュ','cho':'チョ','nya':'ニャ','nyu':'ニュ','nyo':'ニョ','hya':'ヒャ','hyu':'ヒュ','hyo':'ヒョ','mya':'ミャ','myu':'ミュ','myo':'ミョ','rya':'リャ','ryu':'リュ','ryo':'リョ','gya':'ギャ','gyu':'ギュ','gyo':'ギョ','ja':'ジャ','ju':'ジュ','jo':'ジョ','bya':'ビャ','byu':'ビュ','byo':'ビョ','pya':'ピャ','pyu':'ピュ','pyo':'ピョ','fa':'ファ','fi':'フィ','fe':'フェ','fo':'フォ','ti':'ティ','di':'ディ','we':'ウェ','wi':'ウィ','wo':'ウォ','va':'ヴァ','vi':'ヴィ','vu':'ヴ','ve':'ヴェ','vo':'ヴォ','che':'チェ','ka':'カ','ki':'キ','ku':'ク','ke':'ケ','ko':'コ','sa':'サ','shi':'シ','su':'ス','se':'セ','so':'ソ','ta':'タ','chi':'チ','tsu':'ツ','te':'テ','to':'ト','na':'ナ','ni':'ニ','nu':'ヌ','ne':'ネ','no':'ノ','ha':'ハ','hi':'ヒ','fu':'フ','he':'ヘ','ho':'ホ','ma':'マ','mi':'ミ','mu':'ム','me':'メ','mo':'モ','ya':'ヤ','yu':'ユ','yo':'ヨ','ra':'ラ','ri':'リ','ru':'ル','re':'レ','ro':'ロ','wa':'ワ','wo':'ヲ','ga':'ガ','gi':'ギ','gu':'グ','ge':'ゲ','go':'ゴ','za':'ザ','ji':'ジ','zu':'ズ','ze':'ゼ','zo':'ゾ','da':'ダ','de':'デ','do':'ド','ba':'バ','bi':'ビ','bu':'ブ','be':'ベ','bo':'ボ','pa':'パ','pi':'ピ','pu':'プ','pe':'ペ','po':'ポ','a':'ア','i':'イ','u':'ウ','e':'エ','o':'オ','nn':'ン',"n'":'ン','-':'ー'};

const KATA_COURSE_DATA = [
    {
        title: "Módulo 1: As 5 Vogais Básicas", desc: "O Katakana é mais reto e angular. É usado para palavras importadas de outros idiomas.",
        chars: [{ char: "ア", romaji: "a", mnemonic: "Parece a letra 'A' maiúscula distorcida ou uma picareta.", stroke: "2 traços. Um horizontal que dobra, e um descendo." },{ char: "イ", romaji: "i", mnemonic: "Parece uma águia em voo caindo em direção ao chão.", stroke: "2 traços. Um vertical e um caindo à esquerda." },{ char: "ウ", romaji: "u", mnemonic: "Parece o 'u' do hiragana (う), mas com cantos totalmente retos.", stroke: "3 traços. Dois traços curtos no topo e um ângulo." },{ char: "エ", romaji: "e", mnemonic: "Lembra a letra 'I' maiúscula nas fontes clássicas com serifa.", stroke: "3 traços retos horizontais e verticais." },{ char: "オ", romaji: "o", mnemonic: "Um homem cantando 'Ópera' com os braços abertos e uma perna levantada.", stroke: "3 traços. Cruz com gancho lateral." }],
        vocab: [{ kana: "エア", romaji: "ea", meaning: "Ar (Air)" }, { kana: "アイ", romaji: "ai", meaning: "Olho (Eye)" }, { kana: "エイ", romaji: "ei", meaning: "Raia (peixe)" }, { kana: "ウエア", romaji: "uea", meaning: "Roupa (Wear)" },{ kana: "オア", romaji: "oa", meaning: "Minério (Ore)" }, { kana: "イオ", romaji: "io", meaning: "Io (Lua)" }, { kana: "アウ", romaji: "au", meaning: "Exclamação (Ow)" }, { kana: "イエ", romaji: "ie", meaning: "Sim (Yeah)" },{ kana: "ウイ", romaji: "ui", meaning: "Nós (We)" }, { kana: "オイ", romaji: "oi", meaning: "Ei (Oi)" }],
        quiz: [{ q: "Como se escreve 'Air' (ea)?", a: "エア", type: "kana" }, { q: "Qual é a leitura de アイ (Olho)?", a: "ai", type: "romaji" }, { q: "Escreva a vogal 'u'?", a: "ウ", type: "kana" }, { q: "Qual é a leitura de エ?", a: "e", type: "romaji" },{ q: "Escreva 'Wear' (uea)?", a: "ウエア", type: "kana" }, { q: "Leitura de オア?", a: "oa", type: "romaji" }, { q: "Escreva 'Yeah' (ie)?", a: "イエ", type: "kana" }, { q: "Leitura de イオ?", a: "io", type: "romaji" },{ q: "Escreva 'Oi' (oi)?", a: "オイ", type: "kana" }, { q: "Leitura de アウ?", a: "au", type: "romaji" }]
    },
    {
        title: "Módulo 2: K, S, T, N (E o Traço Longo)", desc: "No Katakana, usamos o traço (ー) para indicar uma vogal alongada (ex: sukii = スキー).",
        chars: [{ char: "カ", romaji: "ka", mnemonic: "Igual ao Hiragana か, mas sem o tracinho lateral.", stroke: "2 traços afiados." }, { char: "キ", romaji: "ki", mnemonic: "Igual a き, mas com linhas retas e sem curva inferior.", stroke: "3 traços." }, { char: "ク", romaji: "ku", mnemonic: "Parece o bico de um pássaro 'cuco' ou o sinal de menor (<).", stroke: "2 traços." }, { char: "ケ", romaji: "ke", mnemonic: "Letra 'K' sem a perna vertical esquerda.", stroke: "3 traços." }, { char: "コ", romaji: "ko", mnemonic: "Parecem duas pontas (cantos) de um quadrado ou uma caixa aberta.", stroke: "2 traços." },{ char: "サ", romaji: "sa", mnemonic: "Hiragana さ, mas feito com 3 traços afiados como katanas.", stroke: "3 traços." }, { char: "シ", romaji: "shi", mnemonic: "Uma carinha sorrindo. Traçado sempre de BAIXO para CIMA!", stroke: "3 traços. Os dois pontos olham na horizontal." }, { char: "ス", romaji: "su", mnemonic: "Um cabide de roupas ou uma base de esqui de neve.", stroke: "2 traços." }, { char: "セ", romaji: "se", mnemonic: "Hiragana せ com cantos afiados e retos.", stroke: "2 traços." }, { char: "ソ", romaji: "so", mnemonic: "Traçado sempre de CIMA para BAIXO. Duas agulhas caindo.", stroke: "2 traços." },{ char: "タ", romaji: "ta", mnemonic: "Parece metade da letra K ou uma foice.", stroke: "3 traços." }, { char: "チ", romaji: "chi", mnemonic: "Hiragana ち, mas desenhado com régua e esquadro.", stroke: "3 traços." }, { char: "ツ", romaji: "tsu", mnemonic: "Sorriso largo. Traçado sempre de CIMA para BAIXO!", stroke: "3 traços. Os pontos olham na vertical." }, { char: "テ", romaji: "te", mnemonic: "Placa de telégrafo japonesa (〒).", stroke: "3 traços." }, { char: "ト", romaji: "to", mnemonic: "Um totem ou uma cruz invertida.", stroke: "2 traços." },{ char: "ナ", romaji: "na", mnemonic: "Uma cruz torta ou galho quebrado.", stroke: "2 traços." }, { char: "ニ", romaji: "ni", mnemonic: "Kanji do número 2 (duas barras horizontais).", stroke: "2 traços paralelos." }, { char: "ヌ", romaji: "nu", mnemonic: "Número 7 cortado no meio.", stroke: "2 traços." }, { char: "ネ", romaji: "ne", mnemonic: "Um teto sobre um pedestal.", stroke: "4 traços." }, { char: "ノ", romaji: "no", mnemonic: "O corte diagonal de uma espada de samurai.", stroke: "1 traço." }, { char: "ー", romaji: "(Longo)", mnemonic: "Vogal alongada. Digita-se sempre com o hífen (-).", stroke: "1 traço horizontal." }],
        vocab: [{ kana: "スキー", romaji: "sukii", meaning: "Esqui (Ski)" }, { kana: "ケーキ", romaji: "keeki", meaning: "Bolo (Cake)" }, { kana: "キス", romaji: "kisu", meaning: "Beijo (Kiss)" }, { kana: "テスト", romaji: "tesuto", meaning: "Teste (Test)" },{ kana: "ノート", romaji: "nooto", meaning: "Caderno (Note)" }, { kana: "タクシー", romaji: "takushii", meaning: "Táxi (Taxi)" }, { kana: "ソース", romaji: "soosu", meaning: "Molho (Sauce)" }, { kana: "コネ", romaji: "kone", meaning: "Conexão" },{ kana: "ネクタイ", romaji: "nekutai", meaning: "Gravata" }, { kana: "テント", romaji: "tento", meaning: "Tenda" }],
        quiz: [{ q: "Qual é a leitura de スキー?", a: "sukii", type: "romaji" }, { q: "Escreva 'Cake' (keeki) com traço longo.", a: "ケーキ", type: "kana" }, { q: "Leitura de テスト?", a: "tesuto", type: "romaji" }, { q: "Escreva 'Taxi' (takushii)?", a: "タクシー", type: "kana" },{ q: "Escreva 'Note' (nooto)?", a: "ノート", type: "kana" }, { q: "Leitura de キス?", a: "kisu", type: "romaji" }, { q: "Escreva 'Molho' (soosu)?", a: "ソース", type: "kana" }, { q: "Leitura de ネクタイ?", a: "nekutai", type: "romaji" },{ q: "Escreva 'Tenda' (tento)?", a: "テント", type: "kana" }, { q: "Leitura de コネ?", a: "kone", type: "romaji" }]
    },
    {
        title: "Módulo 3: H, M, Y, R, W, N", desc: "Aqui fechamos o bloco das letras básicas do Katakana.",
        chars: [{ char: "ハ", romaji: "ha", mnemonic: "Uma tenda de acampamento ou o telhado de uma cabana.", stroke: "2 traços abrindo." }, { char: "ヒ", romaji: "hi", mnemonic: "Parece a boca de uma cadeira sorrindo de lado.", stroke: "2 traços." }, { char: "フ", romaji: "fu", mnemonic: "O bico de um pato ou um gancho de guindaste.", stroke: "1 traço." }, { char: "ヘ", romaji: "he", mnemonic: "IDÊNTICO ao Hiragana. É o teto de uma casa.", stroke: "1 traço." }, { char: "ホ", romaji: "ho", mnemonic: "Uma árvore com galhos cortados ou uma cruz sagrada.", stroke: "4 traços." },{ char: "マ", romaji: "ma", mnemonic: "Não confunda com o ア! Parece um triângulo apontando para baixo.", stroke: "2 traços." }, { char: "ミ", romaji: "mi", mnemonic: "Três (mi) mísseis voando em paralelo.", stroke: "3 traços curtos inclinados." }, { char: "ム", romaji: "mu", mnemonic: "Um triângulo isósceles apontando para a direita.", stroke: "2 traços." }, { char: "メ", romaji: "me", mnemonic: "Uma cruz de X em um mapa de tesouro.", stroke: "2 traços cruzados." }, { char: "モ", romaji: "mo", mnemonic: "Idêntico ao Hiragana も, mas muito quadrado e sem laço.", stroke: "3 traços." },{ char: "ヤ", romaji: "ya", mnemonic: "A base do Hiragana や sem o traço extra de corte.", stroke: "2 traços." }, { char: "ユ", romaji: "yu", mnemonic: "Um copo com cantos retos na parte inferior.", stroke: "2 traços." }, { char: "ヨ", romaji: "yo", mnemonic: "Parece um pente com os dentes virados para a esquerda.", stroke: "3 traços." },{ char: "ラ", romaji: "ra", mnemonic: "Uma lanterna presa na parede.", stroke: "2 traços." }, { char: "リ", romaji: "ri", mnemonic: "Hiragana り sem a curvinha de ligação embaixo.", stroke: "2 traços retos verticais." }, { char: "ル", romaji: "ru", mnemonic: "Duas pernas correndo velozes.", stroke: "2 traços." }, { char: "レ", romaji: "re", mnemonic: "Parece um L virado ou um anzol afiado.", stroke: "1 traço." }, { char: "ロ", romaji: "ro", mnemonic: "Um quadrado perfeito ou uma boca aberta (Ro).", stroke: "3 traços fechando a caixa." },{ char: "ワ", romaji: "wa", mnemonic: "Caixa com uma tampa que abre para cima.", stroke: "2 traços." }, { char: "ヲ", romaji: "wo", mnemonic: "Letra F deitada ou um trampolim duplo.", stroke: "3 traços." }, { char: "ン", romaji: "n", mnemonic: "Olho com sorriso subindo. Traçado sempre de BAIXO para CIMA!", stroke: "2 traços. O traço longo sobe cortando." }],
        vocab: [{ kana: "カメラ", romaji: "kamera", meaning: "Câmera" }, { kana: "ホテル", romaji: "hoteru", meaning: "Hotel" }, { kana: "ミルク", romaji: "miruku", meaning: "Leite (Milk)" }, { kana: "ワイン", romaji: "wain", meaning: "Vinho (Wine)" },{ kana: "マウス", romaji: "mausu", meaning: "Mouse / Rato" }, { kana: "メロン", romaji: "meron", meaning: "Melão" }, { kana: "スマホ", romaji: "sumaho", meaning: "Smartphone" }, { kana: "ライオン", romaji: "raion", meaning: "Leão (Lion)" },{ kana: "マイク", romaji: "maiku", meaning: "Microfone" }, { kana: "ルーム", romaji: "ruumu", meaning: "Quarto (Room)" }],
        quiz: [{ q: "Leitura de カメラ?", a: "kamera", type: "romaji" }, { q: "Escreva 'Leite' (miruku)?", a: "ミルク", type: "kana" }, { q: "Leitura de ワイン?", a: "wain", type: "romaji" }, { q: "Escreva 'Hotel' (hoteru)?", a: "ホテル", type: "kana" },{ q: "Escreva 'Smartphone' (sumaho)?", a: "スマホ", type: "kana" }, { q: "Leitura de マウス?", a: "mausu", type: "romaji" }, { q: "Escreva 'Lion' (raion)?", a: "ライオン", type: "kana" }, { q: "Leitura de メロン?", a: "meron", type: "romaji" },{ q: "Escreva 'Quarto' (ruumu)?", a: "ルーム", type: "kana" }, { q: "Leitura de マイク?", a: "maiku", type: "romaji" }]
    },
    {
        title: "Módulo 4: Dakuon (Sonoros)", desc: "Acentos que transformam o som das consoantes: K vira G, S vira Z, T vira D e H vira B.",
        chars: [{ char: "ガ", romaji: "ga", mnemonic: "ka + ゛", stroke: "Adicione os dois tracinhos no topo direito." }, { char: "ギ", romaji: "gi", mnemonic: "ki + ゛", stroke: "A chave angulada com tracinhos." }, { char: "グ", romaji: "gu", mnemonic: "ku + ゛", stroke: "O bico de cuco com tracinhos." }, { char: "ゲ", romaji: "ge", mnemonic: "ke + ゛", stroke: "A letra K modificada ganha tracinhos." }, { char: "ゴ", romaji: "go", mnemonic: "ko + ゛", stroke: "Os dois cantos ganham tracinhos." },{ char: "ザ", romaji: "za", mnemonic: "sa + ゛", stroke: "O 'sa' afiado vira som de Z." }, { char: "ジ", romaji: "ji", mnemonic: "shi + ゛ (Lê-se 'dji')", stroke: "Muito comum em palavras em inglês." }, { char: "ズ", romaji: "zu", mnemonic: "su + ゛", stroke: "O cabide com tracinhos." }, { char: "ゼ", romaji: "ze", mnemonic: "se + ゛", stroke: "O 'se' reto com tracinhos." }, { char: "ゾ", romaji: "zo", mnemonic: "so + ゛", stroke: "As agulhas descendo com tracinhos." },{ char: "ダ", romaji: "da", mnemonic: "ta + ゛", stroke: "A foice ganha tracinhos, virando D." }, { char: "ヂ", romaji: "ji", mnemonic: "chi + ゛", stroke: "Raro em Katakana." }, { char: "ヅ", romaji: "zu", mnemonic: "tsu + ゛", stroke: "Raro em Katakana." }, { char: "デ", romaji: "de", mnemonic: "te + ゛", stroke: "O telégrafo com tracinhos." }, { char: "ド", romaji: "do", mnemonic: "to + ゛", stroke: "A cruz com tracinhos." },{ char: "バ", romaji: "ba", mnemonic: "ha + ゛", stroke: "A tenda com tracinhos vira B." }, { char: "ビ", romaji: "bi", mnemonic: "hi + ゛", stroke: "O sorriso lateral com tracinhos." }, { char: "ブ", romaji: "bu", mnemonic: "fu + ゛", stroke: "O gancho com tracinhos." }, { char: "ベ", romaji: "be", mnemonic: "he + ゛", stroke: "O teto com tracinhos." }, { char: "ボ", romaji: "bo", mnemonic: "ho + ゛", stroke: "A cruz sagrada com tracinhos." }],
        vocab: [{ kana: "バナナ", romaji: "banana", meaning: "Banana" }, { kana: "バス", romaji: "basu", meaning: "Ônibus (Bus)" }, { kana: "テレビ", romaji: "terebi", meaning: "TV (Television)" }, { kana: "パソコン", romaji: "pasokon", meaning: "PC / Computador" },{ kana: "ドア", romaji: "doa", meaning: "Porta (Door)" }, { kana: "ビデオ", romaji: "bideo", meaning: "Vídeo" }, { kana: "ガラス", romaji: "garasu", meaning: "Vidro (Glass)" }, { kana: "ビール", romaji: "biiru", meaning: "Cerveja (Beer)" },{ kana: "ギター", romaji: "gitaa", meaning: "Guitarra / Violão" }, { kana: "ドラゴン", romaji: "doragon", meaning: "Dragão" }],
        quiz: [{ q: "Leitura de バナナ?", a: "banana", type: "romaji" }, { q: "Escreva 'Bus' (basu)?", a: "バス", type: "kana" }, { q: "Leitura de テレビ?", a: "terebi", type: "romaji" }, { q: "Escreva 'PC' (pasokon)?", a: "パソコン", type: "kana" },{ q: "Escreva 'Door' (doa)?", a: "ドア", type: "kana" }, { q: "Leitura de ビール? Lembre do (-)", a: "biiru", type: "romaji" }, { q: "Escreva 'Video' (bideo)?", a: "ビデオ", type: "kana" }, { q: "Leitura de ガラス?", a: "garasu", type: "romaji" },{ q: "Escreva 'Guitarra' (gitaa)?", a: "ギター", type: "kana" }, { q: "Leitura de ドラゴン?", a: "doragon", type: "romaji" }]
    },
    {
        title: "Módulo 5: Handakuon", desc: "A bolinha exclusiva que transforma a coluna do H no som de P em palavras estrangeiras.",
        chars: [{ char: "パ", romaji: "pa", mnemonic: "ha + ゜", stroke: "A tenda ganha uma bolinha estourando (Pop)." },{ char: "ピ", romaji: "pi", mnemonic: "hi + ゜", stroke: "O sorriso ganha bolinha." },{ char: "プ", romaji: "pu", mnemonic: "fu + ゜", stroke: "O gancho com bolinha." },{ char: "ペ", romaji: "pe", mnemonic: "he + ゜", stroke: "O teto com bolinha." },{ char: "ポ", romaji: "po", mnemonic: "ho + ゜", stroke: "A cruz com bolinha." }],
        vocab: [{ kana: "パン", romaji: "pan", meaning: "Pão" }, { kana: "ピアノ", romaji: "piano", meaning: "Piano" }, { kana: "ペン", romaji: "pen", meaning: "Caneta (Pen)" }, { kana: "ポスト", romaji: "posuto", meaning: "Caixa de Correio" },{ kana: "スポーツ", romaji: "supootsu", meaning: "Esportes (Sports)" }, { kana: "ピンク", romaji: "pinku", meaning: "Rosa (Pink)" }, { kana: "プラス", romaji: "purasu", meaning: "Soma/Plus" }, { kana: "ポイント", romaji: "pointo", meaning: "Ponto (Point)" },{ kana: "ページ", romaji: "peeji", meaning: "Página (Page)" }, { kana: "プロ", romaji: "puro", meaning: "Profissional (Pro)" }],
        quiz: [{ q: "Leitura de パン?", a: "pan", type: "romaji" }, { q: "Escreva 'Pen' (pen)?", a: "ペン", type: "kana" }, { q: "Leitura de ピアノ?", a: "piano", type: "romaji" }, { q: "Escreva 'Post' (posuto)?", a: "ポスト", type: "kana" },{ q: "Leitura de スポーツ?", a: "supootsu", type: "romaji" }, { q: "Escreva 'Rosa' (pinku)?", a: "ピンク", type: "kana" }, { q: "Leitura de プラス?", a: "purasu", type: "romaji" }, { q: "Escreva 'Ponto' (pointo)?", a: "ポイント", type: "kana" },{ q: "Leitura de ページ?", a: "peeji", type: "romaji" }, { q: "Escreva 'Profissional' (puro)?", a: "プロ", type: "kana" }]
    },
    {
        title: "Módulo 6: Junções e Sons Estrangeiros", desc: "Como o japonês precisa importar palavras ocidentais, o Katakana criou combinações inéditas com vogais pequenas (fa, ti, wi, che...)...",
        chars: [{ char: "キャ", romaji: "kya", mnemonic: "ki + ya pequeno", stroke: "Ex: キャンプ (kyanpu - acampamento)." }, { char: "ファ", romaji: "fa", mnemonic: "Fu + a pequeno", stroke: "Cria a família do F: ファ(fa), フィ(fi), フェ(fe), フォ(fo)." }, { char: "ティ", romaji: "ti", mnemonic: "Te + i pequeno", stroke: "Cria o som de TI limpo (ex: Party = パーティー)." },{ char: "ウェ", romaji: "we", mnemonic: "U + e pequeno", stroke: "Cria a família do W: ウィ(wi), ウェ(we), ウォ(wo)." }, { char: "ヴィ", romaji: "vi", mnemonic: "Vu (U com dakuten) + i", stroke: "Cria a família do V ocidental: ヴァ(va), ヴィ(vi), ヴェ(ve)." }, { char: "ッ", romaji: "(pausa)", mnemonic: "Pequeno TSU", stroke: "Dobra a consoante seguinte (Sokuon)." }],
        vocab: [{ kana: "フォーク", romaji: "fooku", meaning: "Garfo (Fork)" }, { kana: "パーティー", romaji: "paatii", meaning: "Festa (Party)" }, { kana: "カフェ", romaji: "kafe", meaning: "Café" }, { kana: "シャツ", romaji: "shatsu", meaning: "Camisa (Shirt)" },{ kana: "チョコレート", romaji: "chokoreeto", meaning: "Chocolate" }, { kana: "コンピューター", romaji: "konpyuutaa", meaning: "Computador" }, { kana: "チェック", romaji: "chekku", meaning: "Cheque / Checar" }, { kana: "キャンプ", romaji: "kyanpu", meaning: "Acampamento" },{ kana: "ティッシュ", romaji: "tisshu", meaning: "Lenço de papel (Tissue)" }, { kana: "ニュース", romaji: "nyuusu", meaning: "Notícias (News)" }],
        quiz: [{ q: "Leitura de カフェ?", a: "kafe", type: "romaji" }, { q: "Escreva 'Festa' (paatii)?", a: "パーティー", type: "kana" }, { q: "Leitura de チョコレート?", a: "chokoreeto", type: "romaji" }, { q: "Escreva 'Camisa' (shatsu)?", a: "シャツ", type: "kana" },{ q: "Escreva 'Garfo' (fooku)?", a: "フォーク", type: "kana" }, { q: "Leitura de チェック?", a: "chekku", type: "romaji" }, { q: "Escreva 'Camp' (kyanpu)?", a: "キャンプ", type: "kana" }, { q: "Leitura de コンピューター?", a: "konpyuutaa", type: "romaji" },{ q: "Escreva 'Tissue' (tisshu)?", a: "ティッシュ", type: "kana" }, { q: "Leitura de ニュース?", a: "nyuusu", type: "romaji" }]
    },
    {
        title: "Módulo 7: Guia de Sobrevivência (Tipografia)", desc: "Todo estudante sofre com essas letras parecidas. O segredo está na DIREÇÃO do traçado e na inclinação dos pontos.",
        chars: [{ char: "シ vs ツ", romaji: "Shi e Tsu", mnemonic: "O シ (Shi) sorri de BAIXO para CIMA, com pontos horizontais. O ツ (Tsu) cai de CIMA para BAIXO, com pontos verticais.", stroke: "Sempre olhe para onde os dois tracinhos apontam." },{ char: "ソ vs ン", romaji: "So e N", mnemonic: "ン (N) tem o traço longo subindo de BAIXO para CIMA. O ソ (So) chove de CIMA para BAIXO.", stroke: "O N tem um ângulo mais deitado; o SO é mais em pé." },{ char: "ク vs ワ", romaji: "Ku e Wa", mnemonic: "O ク (Ku) tem um bico livre no topo. O ワ (Wa) usa um traço vertical forte à esquerda cortando o teto.", stroke: "Atenção ao canto superior esquerdo." },{ char: "ア vs マ", romaji: "A e Ma", mnemonic: "ア (A) cruza o traço caindo como uma picareta. マ (Ma) é um triângulo limpo e não cruza no meio.", stroke: "Atenção à interseção das linhas." }],
        vocab: [{ kana: "ツアー", romaji: "tsuaa", meaning: "Tour / Viagem" }, { kana: "シーン", romaji: "shiin", meaning: "Cena (Scene)" }, { kana: "アイス", romaji: "aisu", meaning: "Gelo / Sorvete (Ice)" }, { kana: "ワイン", romaji: "wain", meaning: "Vinho" },{ kana: "マイク", romaji: "maiku", meaning: "Microfone" }, { kana: "シーツ", romaji: "shiitsu", meaning: "Lençóis de cama (Sheets)" }, { kana: "ソース", romaji: "soosu", meaning: "Molho (Sauce)" }, { kana: "ソン", romaji: "son", meaning: "Canção (Song)" },{ kana: "クイズ", romaji: "kuizu", meaning: "Quiz / Jogo de perguntas" }, { kana: "アニメ", romaji: "anime", meaning: "Anime / Animação" }],
        quiz: [{ q: "Leitura de ツアー?", a: "tsuaa", type: "romaji" }, { q: "Escreva Scene (shiin)?", a: "シーン", type: "kana" }, { q: "Leitura de マイク?", a: "maiku", type: "romaji" }, { q: "A letra ン (n) sobe ou desce no traçado?", a: "sobe", type: "romaji" },{ q: "Escreva Ice (aisu)?", a: "アイス", type: "kana" }, { q: "Leitura de シーツ?", a: "shiitsu", type: "romaji" }, { q: "Escreva Song (son)?", a: "ソン", type: "kana" }, { q: "Leitura de クイズ?", a: "kuizu", type: "romaji" },{ q: "Escreva Anime (anime)?", a: "アニメ", type: "kana" }, { q: "Leitura de ソース?", a: "soosu", type: "romaji" }]
    },
    {
        isReferenceTable: true, title: "Módulo 8: Tabela Completa do Katakana", desc: "Seu guia de consulta rápida de sons Katakana, incluindo os estrangeiros. Clique para ouvir!",
        sections: [{ title: "Básicos (Módulos 1 a 3)", cols: 5, items: [...RAW_K.mod1, ...RAW_K.mod2, ...RAW_K.mod3] },{ title: "Dakuon / Sonoros (Módulo 4)", cols: 5, items: RAW_K.mod4 },{ title: "Handakuon (Módulo 5)", cols: 5, items: RAW_K.mod5 },{ title: "Yōon e Estrangeiros (Módulo 6)", cols: 5, items: RAW_K.mod6 }]
    }
];