const RAW_H = {
    mod1: [{k:'あ',r:'a'},{k:'い',r:'i'},{k:'う',r:'u'},{k:'え',r:'e'},{k:'お',r:'o'}],
    mod2: [{k:'か',r:'ka'},{k:'き',r:'ki'},{k:'く',r:'ku'},{k:'け',r:'ke'},{k:'こ',r:'ko'},{k:'さ',r:'sa'},{k:'し',r:'shi'},{k:'す',r:'su'},{k:'せ',r:'se'},{k:'そ',r:'so'},{k:'た',r:'ta'},{k:'ち',r:'chi'},{k:'つ',r:'tsu'},{k:'て',r:'te'},{k:'と',r:'to'},{k:'な',r:'na'},{k:'に',r:'ni'},{k:'ぬ',r:'nu'},{k:'ね',r:'ne'},{k:'の',r:'no'}],
    mod3: [{k:'は',r:'ha'},{k:'ひ',r:'hi'},{k:'ふ',r:'fu'},{k:'へ',r:'he'},{k:'ほ',r:'ho'},{k:'ま',r:'ma'},{k:'み',r:'mi'},{k:'む',r:'mu'},{k:'め',r:'me'},{k:'も',r:'mo'},{k:'や',r:'ya'},{k:'ゆ',r:'yu'},{k:'よ',r:'yo'},{k:'ら',r:'ra'},{k:'り',r:'ri'},{k:'る',r:'ru'},{k:'れ',r:'re'},{k:'ろ',r:'ro'},{k:'わ',r:'wa'},{k:'を',r:'wo'},{k:'ん',r:'n'}],
    mod4: [{k:'が',r:'ga'},{k:'ぎ',r:'gi'},{k:'ぐ',r:'gu'},{k:'げ',r:'ge'},{k:'ご',r:'go'},{k:'ざ',r:'za'},{k:'じ',r:'ji'},{k:'ず',r:'zu'},{k:'ぜ',r:'ze'},{k:'ぞ',r:'zo'},{k:'だ',r:'da'},{k:'ぢ',r:'ji'},{k:'づ',r:'zu'},{k:'で',r:'de'},{k:'ど',r:'do'},{k:'ば',r:'ba'},{k:'び',r:'bi'},{k:'ぶ',r:'bu'},{k:'べ',r:'be'},{k:'ぼ',r:'bo'}],
    mod5: [{k:"ぱ",r:"pa"},{k:"ぴ",r:"pi"},{k:"ぷ",r:"pu"},{k:"ぺ",r:"pe"},{k:"ぽ",r:"po"}],
    mod6: [{k:'きゃ',r:'kya'},{k:'きゅ',r:'kyu'},{k:'きょ',r:'kyo'},{k:'しゃ',r:'sha'},{k:'しゅ',r:'shu'},{k:'しょ',r:'sho'},{k:'ちゃ',r:'cha'},{k:'ちゅ',r:'chu'},{k:'ちょ',r:'cho'},{k:'にゃ',r:'nya'},{k:'にゅ',r:'nyu'},{k:'にょ',r:'nyo'},{k:'ひゃ',r:'hya'},{k:'ひゅ',r:'hyu'},{k:'ひょ',r:'hyo'},{k:'みゃ',r:'mya'},{k:'みゅ',r:'myu'},{k:'みょ',r:'myo'},{k:'りゃ',r:'rya'},{k:'りゅ',r:'ryu'},{k:'りょ',r:'ryo'},{k:'ぎゃ',r:'gya'},{k:'ぎゅ',r:'gyu'},{k:'ぎょ',r:'gyo'},{k:'じゃ',r:'ja'},{k:'じゅ',r:'ju'},{k:'じょ',r:'jo'},{k:'びゃ',r:'bya'},{k:'びゅ',r:'byu'},{k:'びょ',r:'byo'},{k:'ぴゃ',r:'pya'},{k:'ぴゅ',r:'pyu'},{k:'ぴょ',r:'pyo'},{k:'っ',r:'(sokuon)'}],
    words_easy: [{k:'あめ',r:'ame', m:'Chuva', a:['雨', '飴']},{k:'かさ',r:'kasa', m:'Guarda-chuva', a:['傘']},{k:'ねこ',r:'neko', m:'Gato', a:['猫']},{k:'くるま',r:'kuruma', m:'Carro', a:['車']},{k:'いぬ',r:'inu', m:'Cachorro', a:['犬']},{k:'つき',r:'tsuki', m:'Lua', a:['月']},{k:'はな',r:'hana', m:'Flor/Nariz', a:['花', '鼻']},{k:'みず',r:'mizu', m:'Água', a:['水']},{k:'かわ',r:'kawa', m:'Rio', a:['川']},{k:'やま',r:'yama', m:'Montanha', a:['山']},{k:'あき',r:'aki', m:'Outono', a:['秋']},{k:'ふゆ',r:'fuyu', m:'Inverno', a:['冬']},{k:'はる',r:'haru', m:'Primavera', a:['春']},{k:'なつ',r:'natsu', m:'Verão', a:['夏']},{k:'き',r:'ki', m:'Árvore', a:['木']},{k:'くち',r:'kuchi', m:'Boca', a:['口']},{k:'め',r:'me', m:'Olho', a:['目']},{k:'みみ',r:'mimi', m:'Orelha', a:['耳']},{k:'て',r:'te', m:'Mão', a:['手']},{k:'あし',r:'ashi', m:'Pé', a:['足']},{k:'そら',r:'sora', m:'Céu', a:['空']},{k:'ほし',r:'hoshi', m:'Estrela', a:['星']},{k:'うみ',r:'umi', m:'Mar', a:['海']},{k:'いと',r:'ito', m:'Fio', a:['糸']},{k:'むし',r:'mushi', m:'Inseto', a:['虫']}],
    words_medium: [{k:'せんせい',r:'sensei', m:'Professor', a:['先生']},{k:'がっこう',r:'gakkou', m:'Escola', a:['学校']},{k:'ともだち',r:'tomodachi', m:'Amigo', a:['友達']},{k:'さくら',r:'sakura', m:'Cerejeira', a:['桜']},{k:'きっぷ',r:'kippu', m:'Bilhete', a:['切符']},{k:'おちゃ',r:'ocha', m:'Chá verde', a:['お茶']},{k:'でんしゃ',r:'densha', m:'Trem', a:['電車']},{k:'きょう',r:'kyou', m:'Hoje', a:['今日']},{k:'ざっし',r:'zasshi', m:'Revista', a:['雑誌']},{k:'おんがく',r:'ongaku', m:'Música', a:['音楽']},{k:'あした',r:'ashita', m:'Amanhã', a:['明日']},{k:'きのう',r:'kinou', m:'Ontem', a:['昨日']},{k:'あなた',r:'anata', m:'Você', a:['貴方']},{k:'かぞく',r:'kazoku', m:'Família', a:['家族']},{k:'こども',r:'kodomo', m:'Criança', a:['子供']},{k:'さむい',r:'samui', m:'Frio', a:['寒い']},{k:'つめたい',r:'tsumetai', m:'Gelado', a:['冷たい']},{k:'あつい',r:'atsui', m:'Quente', a:['暑い', '熱い']},{k:'ひだり',r:'hidari', m:'Esquerda', a:['左']},{k:'みぎ',r:'migi', m:'Direita', a:['右']},{k:'むずかしい',r:'muzukashii', m:'Difícil', a:['難しい']},{k:'やさしい',r:'yasashii', m:'Fácil/Gentil', a:['優しい', '易しい']},{k:'れきし',r:'rekishi', m:'História', a:['歴史']},{k:'わかる',r:'wakaru', m:'Entender', a:['分かる', '解る']},{k:'おいしい',r:'oishii', m:'Delicioso', a:['美味しい']}],
    words_hard: [{k:'としょかん',r:'toshokan', m:'Biblioteca', a:['図書館']},{k:'びょういん',r:'byouin', m:'Hospital', a:['病院']},{k:'ひらがな',r:'hiragana', m:'Hiragana', a:['平仮名']},{k:'じてんしゃ',r:'jitensha', m:'Bicicleta', a:['自転車']},{k:'しゃしん',r:'shashin', m:'Foto', a:['写真']},{k:'おとうさん',r:'otousan', m:'Pai', a:['お父さん']},{k:'おかあさん',r:'okaasan', m:'Mãe', a:['お母さん']},{k:'きょねん',r:'kyonen', m:'Ano passado', a:['去年']},{k:'ちょうど',r:'choudo', m:'Exatamente', a:['丁度']},{k:'だいがく',r:'daigaku', m:'Universidade', a:['大学']},{k:'けいざい',r:'keizai', m:'Economia', a:['経済']},{k:'げんき',r:'genki', m:'Saudável/Energia', a:['元気']},{k:'こうえん',r:'kouen', m:'Parque', a:['公園']},{k:'しんぶん',r:'shinbun', m:'Jornal', a:['新聞']},{k:'せんしゅう',r:'senshuu', m:'Semana passada', a:['先週']},{k:'らいしゅう',r:'raishuu', m:'Semana que vem', a:['来週']},{k:'とけい',r:'tokei', m:'Relógio', a:['時計']},{k:'ぼうし',r:'boushi', m:'Chapéu', a:['帽子']},{k:'ゆびわ',r:'yubiwa', m:'Anel', a:['指輪']},{k:'れいぞうこ',r:'reizouko', m:'Geladeira', a:['冷蔵庫']},{k:'しんかんせん',r:'shinkansen', m:'Trem bala', a:['新幹線']},{k:'じどうしゃ',r:'jidousha', m:'Automóvel', a:['自動車']},{k:'だいじょうぶ',r:'daijoubu', m:'Tudo bem', a:['大丈夫']},{k:'ありがとう',r:'arigatou', m:'Obrigado', a:['有難う']},{k:'おはよう',r:'ohayou', m:'Bom dia', a:['お早う']}]
};

const ROMAJI_HIRA_MAP = {'kya':'きゃ','kyu':'きゅ','kyo':'きょ','sha':'しゃ','shu':'しゅ','sho':'しょ','cha':'ちゃ','chu':'ちゅ','cho':'ちょ','nya':'にゃ','nyu':'にゅ','nyo':'にょ','hya':'ひゃ','hyu':'ひゅ','hyo':'ひょ','mya':'みゃ','myu':'みゅ','myo':'みょ','rya':'りゃ','ryu':'りゅ','ryo':'りょ','gya':'ぎゃ','gyu':'ぎゅ','gyo':'ぎょ','ja':'じゃ','ju':'じゅ','jo':'じょ','bya':'びゃ','byu':'びゅ','byo':'びょ','pya':'ぴゃ','pyu':'ぴゅ','pyo':'ぴょ','ka':'か','ki':'き','ku':'く','ke':'け','ko':'こ','sa':'さ','shi':'し','su':'す','se':'せ','so':'そ','ta':'た','chi':'ち','tsu':'つ','te':'て','to':'と','na':'な','ni':'に','nu':'ぬ','ne':'ね','no':'の','ha':'は','hi':'ひ','fu':'ふ','he':'へ','ho':'ほ','ma':'ま','mi':'み','mu':'む','me':'め','mo':'も','ya':'や','yu':'ゆ','yo':'よ','ra':'ら','ri':'り','ru':'る','re':'れ','ro':'ろ','wa':'わ','wo':'を','ga':'が','gi':'ぎ','gu':'ぐ','ge':'げ','go':'ご','za':'ざ','ji':'じ','zu':'ず','ze':'ぜ','zo':'ぞ','da':'だ','de':'で','do':'ど','ba':'ば','bi':'び','bu':'ぶ','be':'べ','bo':'ぼ','pa':'ぱ','pi':'ぴ','pu':'ぷ','pe':'ぺ','po':'ぽ','a':'あ','i':'い','u':'う','e':'え','o':'お','nn':'ん',"n'":'ん'};

const HIRA_COURSE_DATA = [
    {
        title: "Módulo 1: As 5 Vogais Básicas", desc: "A ordem fonética no japonês é sempre: A, I, U, E, O.",
        chars: [{ char: "あ", romaji: "a", mnemonic: "Parece a letra 'A' minúscula à mão.", stroke: "3 traços. O 3º traço faz um laço amplo." },{ char: "い", romaji: "i", mnemonic: "Parecem duas letras 'I' lado a lado.", stroke: "2 traços. O traço esquerdo é mais longo." },{ char: "う", romaji: "u", mnemonic: "Parece um Urso de perfil.", stroke: "2 traços. O traço superior é curto." },{ char: "え", romaji: "e", mnemonic: "Lembra um pássaro Exótico pousado.", stroke: "2 traços." },{ char: "お", romaji: "o", mnemonic: "Lembra um jogador de golfe.", stroke: "3 traços. Cuidado para não confundir com あ!" }],
        vocab: [{ kana: "あい", romaji: "ai", meaning: "Amor" }, { kana: "いえ", romaji: "ie", meaning: "Casa" }, { kana: "うえ", romaji: "ue", meaning: "Cima/Sobre" }, { kana: "あお", romaji: "ao", meaning: "Azul" },{ kana: "いう", romaji: "iu", meaning: "Dizer" }, { kana: "おい", romaji: "oi", meaning: "Sobrinho/Ei" }, { kana: "ええ", romaji: "ee", meaning: "Sim (informal)" }, { kana: "あう", romaji: "au", meaning: "Encontrar" },{ kana: "いい", romaji: "ii", meaning: "Bom/Legal" }, { kana: "おいおい", romaji: "oioi", meaning: "Ei ei!/Calma" }],
        quiz: [{ q: "Escreva 'Amor' (ai)?", a: "あい", type: "kana" }, { q: "Leitura de いえ?", a: "ie", type: "romaji" }, { q: "Escreva 'Azul' (ao)?", a: "あお", type: "kana" }, { q: "Leitura de う?", a: "u", type: "romaji" },{ q: "Escreva 'Sim' (ee)?", a: "ええ", type: "kana" }, { q: "Leitura de あう?", a: "au", type: "romaji" }, { q: "Escreva 'Bom' (ii)?", a: "いい", type: "kana" }, { q: "Escreva 'Cima' (ue)?", a: "うえ", type: "kana" },{ q: "Leitura de おい?", a: "oi", type: "romaji" }, { q: "Escreva 'Dizer' (iu)?", a: "いう", type: "kana" }]
    },
    {
        title: "Módulo 2: K, S, T, N", desc: "Combinando consoantes com vogais, seu vocabulário se multiplicará rapidamente!",
        chars: [{ char: "か", romaji: "ka", mnemonic: "Caranguejo com uma patinha.", stroke: "3 traços." }, { char: "き", romaji: "ki", mnemonic: "Parece uma chave (Key).", stroke: "4 traços." }, { char: "く", romaji: "ku", mnemonic: "Bico de Cuco aberto (<).", stroke: "1 traço." }, { char: "け", romaji: "ke", mnemonic: "Duas espadas lado a lado.", stroke: "3 traços." }, { char: "こ", romaji: "ko", mnemonic: "Duas Cordas ou lábios.", stroke: "2 traços." },{ char: "さ", romaji: "sa", mnemonic: "Parece き, mas com UMA linha horizontal.", stroke: "3 traços." }, { char: "し", romaji: "shi", mnemonic: "Lê-se 'xi'. Lembra um anzol.", stroke: "1 traço contínuo." }, { char: "す", romaji: "su", mnemonic: "Super-herói voando em um laço.", stroke: "2 traços." }, { char: "せ", romaji: "se", mnemonic: "Pessoa Sentada no colo de outra.", stroke: "3 traços." }, { char: "そ", romaji: "so", mnemonic: "Costura de ziguezague.", stroke: "1 traço." },{ char: "た", romaji: "ta", mnemonic: "Combinação das letras 't' e 'a'.", stroke: "4 traços." }, { char: "ち", romaji: "chi", mnemonic: "Parece o número 5.", stroke: "2 traços." }, { char: "つ", romaji: "tsu", mnemonic: "Onda de Tsunami.", stroke: "1 traço." }, { char: "て", romaji: "te", mnemonic: "Telha de telhado.", stroke: "1 traço." }, { char: "と", romaji: "to", mnemonic: "Espinho no dedo do pé (Toe).", stroke: "2 traços." },{ char: "な", romaji: "na", mnemonic: "Freira (Nun) ajoelhada rezando.", stroke: "4 traços." }, { char: "に", romaji: "ni", mnemonic: "Joelho (Knee) ou agulha.", stroke: "3 traços." }, { char: "ぬ", romaji: "nu", mnemonic: "Macarrão (Noodles).", stroke: "2 traços. TERMINA com laço!" }, { char: "ね", romaji: "ne", mnemonic: "Gato (Neko) se espreguiçando.", stroke: "2 traços. Termina com laço!" }, { char: "の", romaji: "no", mnemonic: "Símbolo de No (Proibido).", stroke: "1 traço circular." }],
        vocab: [{ kana: "ねこ", romaji: "neko", meaning: "Gato" }, { kana: "いぬ", romaji: "inu", meaning: "Cachorro" }, { kana: "かさ", romaji: "kasa", meaning: "Guarda-chuva" }, { kana: "つくえ", romaji: "tsukue", meaning: "Mesa / Escrivaninha" },{ kana: "なに", romaji: "nani", meaning: "O que?" }, { kana: "あさ", romaji: "asa", meaning: "Manhã" }, { kana: "くつ", romaji: "kutsu", meaning: "Sapatos" }, { kana: "きのう", romaji: "kinou", meaning: "Ontem" },{ kana: "すし", romaji: "sushi", meaning: "Sushi" }, { kana: "たかい", romaji: "takai", meaning: "Alto / Caro" }],
        quiz: [{ q: "Qual a leitura de ねこ?", a: "neko", type: "romaji" }, { q: "Escreva 'Guarda-chuva' (kasa)?", a: "かさ", type: "kana" }, { q: "Leitura de つくえ?", a: "tsukue", type: "romaji" }, { q: "Escreva 'Cachorro' (inu)?", a: "いぬ", type: "kana" },{ q: "Escreva 'Sushi' (sushi)?", a: "すし", type: "kana" }, { q: "Leitura de なに?", a: "nani", type: "romaji" }, { q: "Escreva 'Manhã' (asa)?", a: "あさ", type: "kana" }, { q: "Leitura de たかい?", a: "takai", type: "romaji" },{ q: "Escreva 'Sapatos' (kutsu)?", a: "くつ", type: "kana" }, { q: "Leitura de きのう?", a: "kinou", type: "romaji" }]
    },
    {
        title: "Módulo 3: H, M, Y, R, W, N Final", desc: "Completamos todos os 46 sons básicos do alfabeto Hiragana!",
        chars: [{ char: "は", romaji: "ha", mnemonic: "Tacos de Hóquei sobre o gelo.", stroke: "3 traços." }, { char: "ひ", romaji: "hi", mnemonic: "Sorriso 'Hi-hi-hi'.", stroke: "1 traço." }, { char: "ふ", romaji: "fu", mnemonic: "Monte Fuji.", stroke: "4 traços." }, { char: "へ", romaji: "he", mnemonic: "Teto de uma casa.", stroke: "1 traço." }, { char: "ほ", romaji: "ho", mnemonic: "Chaminé.", stroke: "4 traços." },{ char: "ま", romaji: "ma", mnemonic: "Mastro com vela.", stroke: "3 traços." }, { char: "み", romaji: "mi", mnemonic: "Nota Musical.", stroke: "2 traços." }, { char: "む", romaji: "mu", mnemonic: "Vaca (Muuu).", stroke: "3 traços." }, { char: "め", romaji: "me", mnemonic: "Olho. SEM o laço final!", stroke: "2 traços." }, { char: "も", romaji: "mo", mnemonic: "Anzol.", stroke: "3 traços." },{ char: "や", romaji: "ya", mnemonic: "Yak com chifre.", stroke: "3 traços." }, { char: "ゆ", romaji: "yu", mnemonic: "Peixe U.", stroke: "2 traços." }, { char: "よ", romaji: "yo", mnemonic: "Iô-iô.", stroke: "2 traços." },{ char: "ら", romaji: "ra", mnemonic: "Rato.", stroke: "2 traços." }, { char: "り", romaji: "ri", mnemonic: "Rios paralelos.", stroke: "2 traços." }, { char: "る", romaji: "ru", mnemonic: "Loop de montanha-russa.", stroke: "1 traço." }, { char: "れ", romaji: "re", mnemonic: "Corredor. Sem laço!", stroke: "2 traços." }, { char: "ろ", romaji: "ro", mnemonic: "Road (estrada).", stroke: "1 traço." },{ char: "わ", romaji: "wa", mnemonic: "Vespa.", stroke: "2 traços." }, { char: "を", romaji: "wo", mnemonic: "Atleta. O 'w' é silencioso.", stroke: "3 traços." }, { char: "ん", romaji: "n", mnemonic: "A letra 'n' cursiva!", stroke: "1 traço." }],
        vocab: [{ kana: "さくら", romaji: "sakura", meaning: "Flor de cerejeira" }, { kana: "わたし", romaji: "watashi", meaning: "Eu" }, { kana: "ほん", romaji: "hon", meaning: "Livro" }, { kana: "くるま", romaji: "kuruma", meaning: "Carro" },{ kana: "やま", romaji: "yama", meaning: "Montanha" }, { kana: "はな", romaji: "hana", meaning: "Flor / Nariz" }, { kana: "ほし", romaji: "hoshi", meaning: "Estrela" }, { kana: "ふゆ", romaji: "fuyu", meaning: "Inverno" },{ kana: "ひと", romaji: "hito", meaning: "Pessoa" }, { kana: "まち", romaji: "machi", meaning: "Cidade" }, { kana: "かわ", romaji: "kawa", meaning: "Rio" }, { kana: "うみ", romaji: "umi", meaning: "Mar" }],
        quiz: [{ q: "Qual a leitura de わたし?", a: "watashi", type: "romaji" }, { q: "Escreva 'Livro' (hon)?", a: "ほん", type: "kana" }, { q: "Leitura de さくら?", a: "sakura", type: "romaji" }, { q: "Escreva 'Carro' (kuruma)?", a: "くるま", type: "kana" },{ q: "Escreva 'Montanha' (yama)?", a: "やま", type: "kana" }, { q: "Leitura de ひと?", a: "hito", type: "romaji" }, { q: "Escreva 'Rio' (kawa)?", a: "かわ", type: "kana" }, { q: "Leitura de まち?", a: "machi", type: "romaji" },{ q: "Escreva 'Estrela' (hoshi)?", a: "ほし", type: "kana" }, { q: "Leitura de ふゆ?", a: "fuyu", type: "romaji" }]
    },
    {
        title: "Módulo 4: Dakuon (Sonoros)", desc: "Acentos que transformam as consoantes surdas em sonoras: K vira G, S vira Z, T vira D e H vira B.",
        chars: [{ char: "が", romaji: "ga", mnemonic: "ka + ゛", stroke: "Adicione os dois tracinhos no topo direito para o som de G." }, { char: "ぎ", romaji: "gi", mnemonic: "ki + ゛", stroke: "A chave ganha dois tracinhos sonoros." }, { char: "ぐ", romaji: "gu", mnemonic: "ku + ゛", stroke: "O bico de cuco ganha tracinhos." }, { char: "げ", romaji: "ge", mnemonic: "ke + ゛", stroke: "As espadas ganham tracinhos." }, { char: "ご", romaji: "go", mnemonic: "ko + ゛", stroke: "Duas cordas com tracinhos." },{ char: "ざ", romaji: "za", mnemonic: "sa + ゛", stroke: "O samurai ganha tracinhos, virando som de Z." }, { char: "じ", romaji: "ji", mnemonic: "shi + ゛ (Lê-se 'dji')", stroke: "Exceção fonética! Não se lê 'zi', se lê 'dji'." }, { char: "ず", romaji: "zu", mnemonic: "su + ゛", stroke: "O super-herói com tracinhos." }, { char: "ぜ", romaji: "ze", mnemonic: "se + ゛", stroke: "Pessoa sentada com tracinhos." }, { char: "ぞ", romaji: "zo", mnemonic: "so + ゛", stroke: "O ziguezague ganha tracinhos." },{ char: "だ", romaji: "da", mnemonic: "ta + ゛", stroke: "A coluna do T vira D com os tracinhos." }, { char: "ぢ", romaji: "ji", mnemonic: "chi + ゛", stroke: "Exceção! Raro no dia a dia, lê-se 'dji' igual a じ." }, { char: "づ", romaji: "zu", mnemonic: "tsu + ゛", stroke: "Exceção! Raro no dia a dia, lê-se 'zu' igual a ず." }, { char: "で", romaji: "de", mnemonic: "te + ゛", stroke: "A telha com tracinhos." }, { char: "ど", romaji: "do", mnemonic: "to + ゛", stroke: "O espinho com tracinhos." },{ char: "ば", romaji: "ba", mnemonic: "ha + ゛", stroke: "Toda a família do H vira B com os tracinhos." }, { char: "び", romaji: "bi", mnemonic: "hi + ゛", stroke: "Sorriso com tracinhos." }, { char: "ぶ", romaji: "bu", mnemonic: "fu + ゛", stroke: "Monte Fuji com tracinhos." }, { char: "べ", romaji: "be", mnemonic: "he + ゛", stroke: "Teto com tracinhos." }, { char: "ぼ", romaji: "bo", mnemonic: "ho + ゛", stroke: "Chaminé com tracinhos." }],
        vocab: [{ kana: "かぎ", romaji: "kagi", meaning: "Chave" }, { kana: "めがね", romaji: "megane", meaning: "Óculos" }, { kana: "かぜ", romaji: "kaze", meaning: "Vento / Resfriado" }, { kana: "みず", romaji: "mizu", meaning: "Água" },{ kana: "かぞく", romaji: "kazoku", meaning: "Família" }, { kana: "くだもの", romaji: "kudamono", meaning: "Fruta" }, { kana: "ぶた", romaji: "buta", meaning: "Porco" }, { kana: "べんとう", romaji: "bentou", meaning: "Marmita" },{ kana: "でんわ", romaji: "denwa", meaning: "Telefone" }, { kana: "だいがく", romaji: "daigaku", meaning: "Universidade" }],
        quiz: [{ q: "Qual a leitura de みず (Água)?", a: "mizu", type: "romaji" }, { q: "Escreva 'Chave' (kagi)?", a: "かぎ", type: "kana" },{ q: "Leitura de かぞく (Família)?", a: "kazoku", type: "romaji" }, { q: "Escreva 'Vento' (kaze)?", a: "かぜ", type: "kana" },{ q: "Escreva 'Porco' (buta)?", a: "ぶた", type: "kana" }, { q: "Leitura de くだもの (Fruta)?", a: "kudamono", type: "romaji" },{ q: "Escreva 'Universidade' (daigaku)?", a: "だいがく", type: "kana" }, { q: "Leitura de めがね?", a: "megane", type: "romaji" },{ q: "Escreva 'Telefone' (denwa)?", a: "でんわ", type: "kana" }, { q: "Leitura de べんとう?", a: "bentou", type: "romaji" }]
    },
    {
        title: "Módulo 5: Handakuon", desc: "A exclusiva bolinha (゜) que transforma SOMENTE a família do H no som de P.",
        chars: [{ char: "ぱ", romaji: "pa", mnemonic: "ha + ゜", stroke: "A bolinha lembra uma bolha estourando: Pop! O som de H vira P." },{ char: "ぴ", romaji: "pi", mnemonic: "hi + ゜", stroke: "Sorriso com bolinha no canto superior direito." },{ char: "ぷ", romaji: "pu", mnemonic: "fu + ゜", stroke: "Monte Fuji com bolinha." },{ char: "ぺ", romaji: "pe", mnemonic: "he + ゜", stroke: "Teto com bolinha." },{ char: "ぽ", romaji: "po", mnemonic: "ho + ゜", stroke: "Chaminé com bolinha." }],
        vocab: [{ kana: "さんぽ", romaji: "sanpo", meaning: "Passeio" }, { kana: "えんぴつ", romaji: "enpitsu", meaning: "Lápis" }, { kana: "ぱん", romaji: "pan", meaning: "Pão" }, { kana: "てんぷら", romaji: "tenpura", meaning: "Tempurá" }, { kana: "かんぱい", romaji: "kanpai", meaning: "Saúde! / Brinde" }, { kana: "ぴかぴか", romaji: "pikapika", meaning: "Brilhante (Onomatopeia)" },{ kana: "しんぱい", romaji: "shinpai", meaning: "Preocupação" }, { kana: "おんぷ", romaji: "onpu", meaning: "Nota musical" }, { kana: "てんぽ", romaji: "tenpo", meaning: "Ritmo" }, { kana: "きっぷ", romaji: "kippu", meaning: "Bilhete" }],
        quiz: [{ q: "Leitura de さんぽ (Passeio)?", a: "sanpo", type: "romaji" }, { q: "Escreva 'Lápis' (enpitsu)?", a: "えんぴつ", type: "kana" },{ q: "Leitura de てんぷら?", a: "tenpura", type: "romaji" }, { q: "Escreva 'Pão' (pan)?", a: "ぱん", type: "kana" },{ q: "Escreva o brinde 'Kanpai'?", a: "かんぱい", type: "kana" }, { q: "Leitura de ぴかぴか?", a: "pikapika", type: "romaji" }, { q: "Escreva 'Preocupação' (shinpai)?", a: "しんぱい", type: "kana" }, { q: "Leitura de おんぷ?", a: "onpu", type: "romaji" },{ q: "Escreva 'Ritmo' (tenpo)?", a: "てんぽ", type: "kana" }, { q: "Leitura de きっぷ?", a: "kippu", type: "romaji" }]
    },
    {
        title: "Módulo 6: Junções (Yoon) e Sokuon", desc: "Letras pequenas unem sons em uma única sílaba (Yoon) ou dobram consoantes criando pausas rítmicas (Sokuon).",
        chars: [{ char: "きゃ", romaji: "kya", mnemonic: "ki + ya pequeno", stroke: "Escreve-se com や pela metade do tamanho normal." },{ char: "きゅ", romaji: "kyu", mnemonic: "ki + yu pequeno", stroke: "Junção rápida de ki e yu." },{ char: "きょ", romaji: "kyo", mnemonic: "ki + yo pequeno", stroke: "Junção rápida de ki e yo." },{ char: "しゃ", romaji: "sha", mnemonic: "shi + ya pequeno", stroke: "Atenção: Não é 'shia', é 'sha' em som único." },{ char: "しゅ", romaji: "shu", mnemonic: "shi + yu pequeno", stroke: "Som contínuo 'shu'." },{ char: "しょ", romaji: "sho", mnemonic: "shi + yo pequeno", stroke: "Som contínuo 'sho'." },{ char: "ちゃ", romaji: "cha", mnemonic: "chi + ya pequeno", stroke: "Som 'tcha'." },{ char: "ちゅ", romaji: "chu", mnemonic: "chi + yu pequeno", stroke: "Som 'tchu'." },{ char: "ちょ", romaji: "cho", mnemonic: "chi + yo pequeno", stroke: "Som 'tcho'." },{ char: "にゃ", romaji: "nya", mnemonic: "ni + ya pequeno", stroke: "O som clássico dos gatos nos animes!" },{ char: "にゅ", romaji: "nyu", mnemonic: "ni + yu pequeno", stroke: "Junção nasal." },{ char: "にょ", romaji: "nyo", mnemonic: "ni + yo pequeno", stroke: "Junção nasal." },{ char: "ひゃ", romaji: "hya", mnemonic: "hi + ya pequeno", stroke: "Junção aspirada." },{ char: "ひゅ", romaji: "hyu", mnemonic: "hi + yu pequeno", stroke: "Junção aspirada." },{ char: "ひょ", romaji: "hyo", mnemonic: "hi + yo pequeno", stroke: "Junção aspirada." },{ char: "みゃ", romaji: "mya", mnemonic: "mi + ya pequeno", stroke: "Junção labial." },{ char: "みゅ", romaji: "myu", mnemonic: "mi + yu pequeno", stroke: "Junção labial." },{ char: "みょ", romaji: "myo", mnemonic: "mi + yo pequeno", stroke: "Junção labial." },{ char: "りゃ", romaji: "rya", mnemonic: "ri + ya pequeno", stroke: "O 'r' japonês vibrado." },{ char: "りゅ", romaji: "ryu", mnemonic: "ri + yu pequeno", stroke: "Significa dragão!" },{ char: "りょ", romaji: "ryo", mnemonic: "ri + yo pequeno", stroke: "Junção vibrada." },{ char: "ぎゃ", romaji: "gya", mnemonic: "gi + ya pequeno", stroke: "Versão sonora com dakuten." },{ char: "じゃ", romaji: "ja", mnemonic: "ji + ya pequeno", stroke: "Som de 'dja'." },{ char: "びゃ", romaji: "bya", mnemonic: "bi + ya pequeno", stroke: "Junção sonora B." },{ char: "ぴゃ", romaji: "pya", mnemonic: "pi + ya pequeno", stroke: "Junção com handakuon P." },{ char: "っ", romaji: "(sokuon)", mnemonic: "TSU pequeno (Pausa rítmica)", stroke: "Dobra a consoante seguinte (ex: gakkou). Não se pronuncia, faz um breve silêncio na fala!" }],
        vocab: [{ kana: "おちゃ", romaji: "ocha", meaning: "Chá verde" }, { kana: "しゃしん", romaji: "shashin", meaning: "Foto" }, { kana: "じてんしゃ", romaji: "jitensha", meaning: "Bicicleta" }, { kana: "びょういん", romaji: "byouin", meaning: "Hospital" },{ kana: "きょう", romaji: "kyou", meaning: "Hoje" }, { kana: "じしょ", romaji: "jisho", meaning: "Dicionário" }, { kana: "ぎゅうにゅう", romaji: "gyuunyuu", meaning: "Leite de vaca" }, { kana: "がっこう", romaji: "gakkou", meaning: "Escola (Pequeno tsu)" },{ kana: "でんしゃ", romaji: "densha", meaning: "Trem" }, { kana: "きょねん", romaji: "kyonen", meaning: "Ano passado" }],
        quiz: [{ q: "Qual a leitura de おちゃ?", a: "ocha", type: "romaji" }, { q: "Escreva 'Foto' (shashin)?", a: "しゃしん", type: "kana" },{ q: "Escreva 'Bicicleta' (jitensha)?", a: "じてんしゃ", type: "kana" }, { q: "Leitura de びょういん (Hospital)?", a: "byouin", type: "romaji" },{ q: "Escreva 'Hoje' (kyou)?", a: "きょう", type: "kana" }, { q: "Escreva 'Escola' (gakkou) com pequeno tsu?", a: "がっこう", type: "kana" },{ q: "Leitura de じしょ?", a: "jisho", type: "romaji" }, { q: "Escreva 'Leite' (gyuunyuu)?", a: "ぎゅうにゅう", type: "kana" },{ q: "Leitura de でんしゃ?", a: "densha", type: "romaji" }, { q: "Escreva 'Ano passado' (kyonen)?", a: "きょねん", type: "kana" }]
    },
    {
        title: "Módulo 7: Frases e Partículas", desc: "Aprenda as 3 letras que mudam de som quando viram partículas gramaticais e leia frases inteiras sem espaços!",
        chars: [{ char: "は (wa)", romaji: "wa", mnemonic: "Indica o TÓPICO da frase. Escreve-se 'ha', mas pronuncia-se 'wa'.", stroke: "Exemplo: わたしは (watashi wa - Quanto a mim...)" },{ char: "へ (e)", romaji: "e", mnemonic: "Indica DIREÇÃO ou destino. Escreve-se 'he', mas pronuncia-se 'e'.", stroke: "Exemplo: にほんへ (Nihon e - Para o Japão)" },{ char: "を (o)", romaji: "o", mnemonic: "Partícula de OBJETO direto. O 'w' é silencioso no dia a dia.", stroke: "Exemplo: ほんをよむ (hon o yomu - Ler um livro)" }],
        vocab: [{ kana: "わたしはねこがすきです", romaji: "watashi wa neko ga suki desu", meaning: "Eu gosto de gatos. (は = wa)" },{ kana: "きのうほんをよみました", romaji: "kinou hon o yomimashita", meaning: "Ontem eu li um livro. (を = o)" },{ kana: "くるまでがっこうへいきます", romaji: "kuruma de gakkou e ikimasu", meaning: "Vou para a escola de carro. (へ = e)" },{ kana: "せんせいはにほんへいきます", romaji: "sensei wa nihon e ikimasu", meaning: "O professor vai para o Japão." },{ kana: "おちゃをのみます", romaji: "ocha o nomimasu", meaning: "Bebo chá verde." },{ kana: "これはなんですか", romaji: "kore wa nan desu ka", meaning: "O que é isto?" },{ kana: "いぬはそこへいきます", romaji: "inu wa soko e ikimasu", meaning: "O cachorro vai para lá." },{ kana: "あさごはんをたべます", romaji: "asagohan o tabemasu", meaning: "Como o café da manhã." },{ kana: "わたしはがくせいです", romaji: "watashi wa gakusei desu", meaning: "Eu sou estudante." },{ kana: "どこへいきますか", romaji: "doko e ikimasu ka", meaning: "Para onde você vai?" }],
        quiz: [{ q: "Na frase 'わたしは...', pronuncia a partícula は?", a: "wa", type: "romaji" },{ q: "Escreva a partícula de objeto (o/wo)?", a: "を", type: "kana" },{ q: "Escreva 'Bebo chá verde' (ocha o nomimasu)?", a: "おちゃをのみます", type: "kana" },{ q: "Qual a leitura de へ na frase 'がっこうへ'?", a: "e", type: "romaji" },{ q: "Escreva 'O que é isto?' (kore wa nan desu ka)?", a: "これはなんですか", type: "kana" },{ q: "Na frase 'きのうほんをよみました', qual letra é o objeto?", a: "を", type: "kana" },{ q: "Escreva 'Eu sou estudante' (watashi wa gakusei desu)?", a: "わたしはがくせいです", type: "kana" },{ q: "Leitura de どこへいきますか?", a: "doko e ikimasu ka", type: "romaji" },{ q: "Escreva 'Vou para o Japão' (nihon e ikimasu)?", a: "にほんへいきます", type: "kana" },{ q: "Leitura de あさごはんをたべます?", a: "asagohan o tabemasu", type: "romaji" }]
    },
    {
        isReferenceTable: true, title: "Módulo 8: Tabela Completa do Hiragana", desc: "Seu guia de consulta rápida. Clique em qualquer bloco para ouvir a pronúncia nativa!",
        sections: [{ title: "Básicos (Módulos 1 a 3)", cols: 5, items: [...RAW_H.mod1, ...RAW_H.mod2, ...RAW_H.mod3] },{ title: "Dakuon / Sonoros (Módulo 4)", cols: 5, items: RAW_H.mod4 },{ title: "Handakuon (Módulo 5)", cols: 5, items: RAW_H.mod5 },{ title: "Yōon / Junções (Módulo 6)", cols: 3, items: RAW_H.mod6 }]
    }
];